# Generated by Django 4.0.4 on 2022-06-09 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=200)),
                ('data_expedicao', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 17, 17, 51, 551136))),
                ('data_fim', models.DateField()),
                ('remedio', models.ManyToManyField(to='receita.remedio')),
            ],
        ),
    ]
