# Generated by Django 4.0.4 on 2022-06-09 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_pessoa_agenda_remove_pessoa_disponivel_and_more'),
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastro.pessoa'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_expedicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 18, 22, 35, 998275)),
        ),
    ]
