# Generated by Django 4.0.4 on 2022-06-09 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_receita_paciente_alter_receita_data_expedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_expedicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 18, 34, 7, 142366)),
        ),
    ]
