# Generated by Django 4.0.4 on 2022-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cargo',
            field=models.CharField(choices=[('', 'Cargo'), ('P', 'Psicólogo'), ('C', 'Pessoa')], default='', max_length=15),
        ),
    ]
