# Generated by Django 4.0.4 on 2022-06-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_account_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='em_atendimento',
        ),
    ]
