# Generated by Django 4.0.4 on 2022-06-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0004_account_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('finalizado', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa')),
                ('psicologo_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.psicologo')),
            ],
        ),
    ]
