# Generated by Django 4.0.4 on 2022-06-03 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_account_cargo'),
        ('consultar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='psicologo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.psicologo'),
        ),
    ]
