# Generated by Django 4.0.4 on 2022-06-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultar', '0002_alter_consulta_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='finalizado',
        ),
    ]
